from enum import Enum


class CodigoError(Enum):
    SEQUENCE_ERROR = "SEQUENCE_ERROR"
    NOT_ALLOWED_AFTER_AUTHORIZATION = "NOT_ALLOWED_AFTER_AUTHORIZATION"
    REQUIRES_REAUTH = "REQUIRES_REAUTH"
    NO_SERVICES = "NO_SERVICES"
    INVALID_AMOUNT = "INVALID_AMOUNT"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    ORDER_CANCELLED = "ORDER_CANCELLED"
    INVALID_STATE = "INVALID_STATE"
    INVALID_OPERATION = "INVALID_OPERATION"

