from enum import Enum


class EstadoOrden(Enum):
    CREATED = "CREATED"
    DIAGNOSED = "DIAGNOSED"
    AUTHORIZED = "AUTHORIZED"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    WAITING_FOR_APPROVAL = "WAITING_FOR_APPROVAL"
    DELIVERED = "DELIVERED"
    CANCELLED = "CANCELLED"

